set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

create_clock -period 40.000 -name clk [get_ports "clk"]
set_property  IOSTANDARD LVCMOS15 [get_ports rst]
set_property  PACKAGE_PIN AF10 [get_ports rst]
set_property PACKAGE_PIN AA10 [get_ports {sw[0]}]
set_property PACKAGE_PIN AB10 [get_ports {sw[1]}]
set_property PACKAGE_PIN AA13 [get_ports {sw[2]}]
set_property PACKAGE_PIN AA12 [get_ports {sw[3]}]
set_property PACKAGE_PIN Y13 [get_ports {sw[4]}]
set_property PACKAGE_PIN Y12 [get_ports {sw[5]}]
set_property PACKAGE_PIN AD11 [get_ports {sw[6]}]
set_property PACKAGE_PIN AD10 [get_ports {sw[7]}]
set_property PACKAGE_PIN AF12 [get_ports {hl1}]
set_property PACKAGE_PIN AE8 [get_ports {hl2}]
set_property PACKAGE_PIN AF8 [get_ports {hl3}]
set_property PACKAGE_PIN AE13 [get_ports {hl4}]
set_property PACKAGE_PIN AF13 [get_ports {mod}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {mod}]
set_property IOSTANDARD LVCMOS15 [get_ports {hl1}]
set_property IOSTANDARD LVCMOS15 [get_ports {hl2}]
set_property IOSTANDARD LVCMOS15 [get_ports {hl3}]
set_property IOSTANDARD LVCMOS15 [get_ports {hl4}]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {R[0]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {R[1]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {R[2]}]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {R[3]}]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {G[0]}]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {G[1]}]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {G[2]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {G[3]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {B[0]}]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {B[1]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {B[2]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {B[3]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports VS]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports HS]